// Datos de platos peruanos
const platosPeruanos = [
  {
    id: 1,
    nombre: "Ceviche",
    categoria: "entrada",
    descripcion: "El plato bandera del Perú, preparado con pescado fresco marinado en limón.",
    imagen: "https://drive.google.com/file/d/18rxshXKolLXi7fpuVRZVGmDJq8qdn4y3/view?usp=drive_link",
    ingredientes: [
      "500g de pescado blanco fresco (corvina, lenguado o mero)",
      "1 cebolla roja cortada en juliana",
      "2 ajíes limo picados",
      "1 ají amarillo picado",
      "10-12 limones (para el jugo)",
      "1 rama de cilantro picado",
      "1 diente de ajo molido",
      "Sal y pimienta al gusto",
      "Camote cocido",
      "Choclo cocido",
      "Lechuga",
    ],
    preparacion: [
      "Cortar el pescado en cubos de 2 cm aproximadamente.",
      "En un bowl, mezclar el pescado con el ajo molido, sal y pimienta.",
      "Exprimir los limones y agregar el jugo al pescado.",
      "Añadir la cebolla, el ají limo y el ají amarillo.",
      "Mezclar bien y dejar reposar por 3-5 minutos.",
      "Agregar el cilantro picado y mezclar nuevamente.",
      "Servir inmediatamente acompañado de camote, choclo y lechuga.",
    ],
  },
  {
    id: 2,
    nombre: "Lomo Saltado",
    categoria: "principal",
    descripcion: "Deliciosa fusión de la cocina peruana y china, con carne de res salteada con verduras.",
    imagen: "https://drive.google.com/file/d/1f6PYbk3GUGIJn9ut-BtZh6x1BXtYXzYZ/view?usp=drive_link",
    ingredientes: [
      "500g de lomo de res cortado en tiras",
      "2 cebollas rojas cortadas en gajos",
      "2 tomates cortados en gajos",
      "2 ajíes amarillos cortados en tiras",
      "3 dientes de ajo picados",
      "1/4 taza de sillao (salsa de soya)",
      "2 cucharadas de vinagre tinto",
      "1/2 taza de cilantro picado",
      "Aceite vegetal",
      "Sal y pimienta al gusto",
      "500g de papas amarillas",
      "2 tazas de arroz cocido",
    ],
    preparacion: [
      "Freír las papas cortadas en bastones y reservar.",
      "En un wok o sartén grande, calentar aceite a fuego alto.",
      "Saltear el ajo y el ají amarillo por unos segundos.",
      "Agregar la carne y saltear hasta que esté dorada.",
      "Añadir la cebolla y saltear por 1 minuto más.",
      "Incorporar el tomate y saltear brevemente.",
      "Agregar el sillao y el vinagre, mezclar bien.",
      "Sazonar con sal y pimienta al gusto.",
      "Añadir el cilantro picado y mezclar.",
      "Servir inmediatamente con arroz blanco y las papas fritas.",
    ],
  },
  {
    id: 3,
    nombre: "Ají de Gallina",
    categoria: "principal",
    descripcion: "Cremoso guiso de pollo deshilachado en una salsa de ají amarillo y nueces.",
    imagen: "https://drive.google.com/file/d/1iYCOUvVEGdCRAQEt3cEEqlRmRUjM89jL/view?usp=drive_link",
    ingredientes: [
      "1 gallina o pollo entero",
      "4 ajíes amarillos sin venas ni semillas",
      "2 cebollas picadas",
      "3 dientes de ajo",
      "100g de nueces o pecanas",
      "100g de queso parmesano rallado",
      "4 rebanadas de pan de molde remojado en leche",
      "1 taza de leche evaporada",
      "Aceite vegetal",
      "Sal y pimienta al gusto",
      "4 papas amarillas cocidas",
      "3 huevos duros",
      "Aceitunas negras",
      "Arroz blanco cocido",
    ],
    preparacion: [
      "Cocer la gallina o pollo en agua con sal, cebolla y apio. Reservar el caldo.",
      "Desmenuzar la carne y reservar.",
      "En una sartén, sofreír la cebolla y el ajo en aceite hasta que estén transparentes.",
      "Licuar los ajíes amarillos con un poco de caldo de pollo.",
      "Añadir los ajíes licuados a la sartén y cocinar por 5 minutos.",
      "Licuar las nueces, el pan remojado en leche y el queso parmesano con un poco de caldo.",
      "Agregar esta mezcla a la sartén y cocinar por 10 minutos más.",
      "Incorporar la carne desmenuzada y la leche evaporada.",
      "Cocinar a fuego lento por 15 minutos, revolviendo ocasionalmente.",
      "Servir sobre papas amarillas cocidas, decorar con huevo duro en rodajas y aceitunas negras.",
      "Acompañar con arroz blanco.",
    ],
  },
  {
    id: 4,
    nombre: "Causa Limeña",
    categoria: "entrada",
    descripcion: "Terrina fría de papa amarilla rellena de pollo, atún o mariscos.",
    imagen: "https://drive.google.com/file/d/1jXrUiA941LgEVZbRiq4zldJbFKd1TJ1e/view?usp=drive_link",
    ingredientes: [
      "1kg de papas amarillas",
      "3 limones (jugo)",
      "3 ajíes amarillos licuados",
      "3 cucharadas de aceite vegetal",
      "Sal y pimienta al gusto",
      "300g de pollo cocido y deshilachado",
      "1/2 taza de mayonesa",
      "1 cebolla roja picada finamente",
      "1 palta (aguacate)",
      "2 huevos duros",
      "Aceitunas negras",
      "Hojas de lechuga",
    ],
    preparacion: [
      "Cocer las papas con cáscara, pelarlas y pasarlas por un prensapapas.",
      "Mezclar la papa con el jugo de limón, el ají amarillo licuado, aceite, sal y pimienta hasta formar una masa homogénea.",
      "Mezclar el pollo deshilachado con mayonesa, cebolla picada, sal y pimienta.",
      "En un molde rectangular, colocar una capa de la masa de papa.",
      "Añadir el relleno de pollo y cubrir con otra capa de papa.",
      "Refrigerar por al menos 1 hora.",
      "Desmoldar y decorar con rodajas de huevo duro, palta, aceitunas y hojas de lechuga.",
    ],
  },
  {
    id: 5,
    nombre: "Anticuchos",
    categoria: "entrada",
    descripcion: "Brochetas de corazón de res marinadas en una salsa de ají panca y especias.",
    imagen: "https://drive.google.com/file/d/1sf3MxONZgcd5ixHOHcQunT4WzDmujxZU/view?usp=drive_link",
    ingredientes: [
      "1kg de corazón de res",
      "4 cucharadas de pasta de ají panca",
      "3 dientes de ajo molidos",
      "1/4 taza de vinagre tinto",
      "1 cucharadita de comino",
      "1 cucharadita de orégano",
      "Sal y pimienta al gusto",
      "Palitos de brocheta remojados en agua",
      "Papas cocidas",
      "Choclo cocido",
      "Salsa criolla (cebolla, limón, cilantro)",
    ],
    preparacion: [
      "Limpiar el corazón de res y cortarlo en cubos de 3 cm aproximadamente.",
      "Preparar la marinada mezclando el ají panca, ajo, vinagre, comino, orégano, sal y pimienta.",
      "Marinar los trozos de corazón por al menos 4 horas, idealmente toda la noche.",
      "Ensartar los trozos de corazón en los palitos de brocheta.",
      "Cocinar en una parrilla caliente, volteando y pintando con la marinada.",
      "Servir caliente acompañado de papas, choclo y salsa criolla.",
    ],
  },
  {
    id: 6,
    nombre: "Rocoto Relleno",
    categoria: "principal",
    descripcion: "Plato típico de Arequipa, consiste en rocotos rellenos de carne y gratinados con queso.",
    imagen: "https://drive.google.com/file/d/1z7jM2yuK-jnD4BIHB-LGpjW3Mut0auvt/view?usp=drive_link",
    ingredientes: [
      "6 rocotos grandes",
      "500g de carne molida de res",
      "200g de carne molida de cerdo",
      "2 cebollas picadas",
      "3 dientes de ajo picados",
      "1/2 taza de pasas",
      "1/2 taza de aceitunas negras picadas",
      "1/4 taza de maní tostado y molido",
      "2 huevos duros picados",
      "1 cucharadita de comino",
      "1 cucharadita de orégano",
      "200g de queso parmesano rallado",
      "Sal y pimienta al gusto",
      "Papas para el pastel de papas",
    ],
    preparacion: [
      "Cortar la parte superior de los rocotos y retirar las semillas y venas. Reservar las tapas.",
      "Hervir los rocotos en agua con sal y azúcar, cambiando el agua 3 veces para reducir el picante.",
      "En una sartén, sofreír la cebolla y el ajo hasta que estén transparentes.",
      "Añadir las carnes molidas y cocinar hasta que estén doradas.",
      "Agregar las pasas, aceitunas, maní, huevos duros, comino y orégano.",
      "Sazonar con sal y pimienta al gusto.",
      "Rellenar los rocotos con esta mezcla y cubrir con queso parmesano.",
      "Colocar las tapas de los rocotos.",
      "Hornear a 180°C por 20 minutos o hasta que el queso esté dorado.",
      "Servir con pastel de papas.",
    ],
  },
  {
    id: 7,
    nombre: "Arroz con Pato",
    categoria: "principal",
    descripcion: "Plato típico del norte del Perú, con pato cocido en cerveza negra y servido con arroz verde.",
    imagen: "https://drive.google.com/file/d/1rNbeXpP9GcsLIrVd13_l-jNnAv86SeWH/view?usp=drive_link",
    ingredientes: [
      "1 pato entero cortado en presas",
      "3 tazas de arroz",
      "1 manojo grande de culantro (cilantro)",
      "2 ajíes amarillos picados",
      "1 cerveza negra",
      "1 taza de chicha de jora",
      "1 cebolla roja picada",
      "4 dientes de ajo picados",
      "1 pimiento rojo picado",
      "1 zanahoria picada",
      "1 taza de arvejas frescas",
      "Sal y pimienta al gusto",
      "Aceite vegetal",
    ],
    preparacion: [
      "Licuar el culantro con un poco de agua para obtener el jugo verde.",
      "Sazonar el pato con sal y pimienta y dorarlo en una olla grande con aceite caliente.",
      "Retirar el pato y en la misma olla, sofreír la cebolla, ajo, ají amarillo y pimiento.",
      "Regresar el pato a la olla y añadir la cerveza negra y la chicha de jora.",
      "Cocinar a fuego medio por 30 minutos o hasta que el pato esté tierno.",
      "Retirar el pato y reservar el caldo.",
      "En otra olla, sofreír el arroz con un poco de aceite.",
      "Añadir el caldo reservado y el jugo de culantro.",
      "Agregar la zanahoria y las arvejas.",
      "Cocinar el arroz hasta que esté listo.",
      "Servir el arroz con las presas de pato encima.",
    ],
  },
  {
    id: 8,
    nombre: "Suspiro a la Limeña",
    categoria: "postre",
    descripcion: "Dulce tradicional limeño a base de manjar blanco y merengue.",
    imagen: "https://drive.google.com/file/d/10cttxjbv9DPUtYcI0Oe0sw8zNkC_JmQB/view?usp=drive_link",
    ingredientes: [
      "1 lata de leche evaporada",
      "1 lata de leche condensada",
      "5 yemas de huevo",
      "1 cucharadita de vainilla",
      "1/4 taza de oporto o pisco (opcional)",
      "3 claras de huevo",
      "1/2 taza de azúcar",
      "Canela en polvo para decorar",
    ],
    preparacion: [
      "En una olla, mezclar la leche evaporada y la leche condensada.",
      "Cocinar a fuego medio, revolviendo constantemente hasta que espese (aproximadamente 45 minutos).",
      "Retirar del fuego y dejar enfriar un poco.",
      "Añadir las yemas de huevo batidas, la vainilla y el licor. Mezclar bien.",
      "Regresar al fuego bajo y cocinar por 5 minutos más, sin dejar de revolver.",
      "Verter la mezcla en copas individuales y dejar enfriar.",
      "Para el merengue, batir las claras a punto de nieve y agregar el azúcar gradualmente.",
      "Decorar las copas con el merengue y espolvorear canela en polvo.",
      "Refrigerar por al menos 2 horas antes de servir.",
    ],
  },
  {
    id: 9,
    nombre: "Mazamorra Morada",
    categoria: "postre",
    descripcion: "Postre tradicional peruano elaborado con maíz morado y frutas.",
    imagen: "https://drive.google.com/file/d/1-oFRiCrxLkHyUUjMUsdYKLG6EkeI49ac/view?usp=drive_link",
    ingredientes: [
      "500g de maíz morado",
      "2 manzanas peladas y picadas",
      "2 membrillos pelados y picados",
      "100g de guindones (ciruelas secas)",
      "100g de orejones (duraznos secos)",
      "1 piña picada en cubos",
      "Cáscara de 1 naranja",
      "3 ramas de canela",
      "5 clavos de olor",
      "200g de azúcar",
      "150g de fécula de papa o maizena",
      "Jugo de 1 limón",
    ],
    preparacion: [
      "Lavar bien el maíz morado y colocarlo en una olla grande con 3 litros de agua.",
      "Añadir la canela, clavos de olor y cáscara de naranja.",
      "Hervir por 45 minutos, colar y reservar el líquido.",
      "En el líquido, cocinar las frutas picadas por 15 minutos.",
      "Disolver la fécula en 1/2 taza de agua fría.",
      "Añadir el azúcar al líquido y luego la fécula disuelta, revolviendo constantemente.",
      "Cocinar por 5 minutos más hasta que espese.",
      "Agregar el jugo de limón y mezclar.",
      "Servir frío o caliente, según preferencia.",
    ],
  },
  {
    id: 10,
    nombre: "Tacu Tacu",
    categoria: "principal",
    descripcion: "Plato tradicional peruano hecho con arroz y frijoles refritos, formando una tortilla.",
    imagen: "https://drive.google.com/file/d/11-02DvlgT6eQjvVgNviGrJr0NT_eGnQv/view?usp=drive_link",
    ingredientes: [
      "2 tazas de frijoles canarios cocidos",
      "2 tazas de arroz cocido",
      "1 cebolla roja picada",
      "2 dientes de ajo picados",
      "1 ají amarillo picado",
      "1 cucharadita de orégano",
      "Aceite vegetal",
      "Sal y pimienta al gusto",
      "2 huevos fritos (opcional)",
      "2 filetes de bistec (opcional)",
      "Plátano frito (opcional)",
      "Salsa criolla (opcional)",
    ],
    preparacion: [
      "En una sartén, sofreír la cebolla, ajo y ají amarillo hasta que estén transparentes.",
      "Añadir los frijoles cocidos y aplastarlos ligeramente con una cuchara.",
      "Incorporar el arroz cocido y el orégano. Mezclar bien.",
      "Sazonar con sal y pimienta al gusto.",
      "Formar una tortilla con la mezcla y dorarla por ambos lados en aceite caliente.",
      "Servir con huevo frito, bistec, plátano frito y salsa criolla, si se desea.",
    ],
  },
  {
    id: 11,
    nombre: "Picarones",
    categoria: "postre",
    descripcion: "Dulce tradicional peruano similar a las donas, hecho con calabaza y camote.",
    imagen: "https://drive.google.com/file/d/1zUqXE7c1B3Q0QAXECJql5HjIhOxufAty/view?usp=drive_link",
    ingredientes: [
      "500g de calabaza",
      "300g de camote naranja",
      "500g de harina de trigo",
      "25g de levadura fresca",
      "1 cucharadita de anís",
      "1 cucharadita de canela molida",
      "1/4 taza de azúcar",
      "Aceite para freír",
      "Para la miel:",
      "500g de chancaca (panela)",
      "2 tazas de agua",
      "2 ramas de canela",
      "3 clavos de olor",
      "Cáscara de 1 naranja",
      "1 cucharadita de anís",
    ],
    preparacion: [
      "Cocer la calabaza y el camote hasta que estén tiernos. Pelar y hacer un puré.",
      "Disolver la levadura en 1/2 taza de agua tibia con una cucharada de azúcar.",
      "Mezclar el puré con la levadura disuelta, anís, canela y el resto del azúcar.",
      "Añadir la harina poco a poco hasta formar una masa suave y elástica.",
      "Dejar reposar la masa por 1 hora o hasta que duplique su volumen.",
      "Para la miel, hervir la chancaca con agua, canela, clavos, cáscara de naranja y anís hasta que espese.",
      "Calentar abundante aceite en una olla.",
      "Con las manos mojadas, tomar porciones de masa y formar aros, dejándolos caer directamente en el aceite caliente.",
      "Freír hasta que estén dorados por ambos lados.",
      "Escurrir sobre papel absorbente y bañar con la miel caliente antes de servir.",
    ],
  },
  {
    id: 12,
    nombre: "Ocopa Arequipeña",
    categoria: "entrada",
    descripcion:
      "Plato típico de Arequipa que consiste en papas sancochadas bañadas en una cremosa salsa de ají amarillo, huacatay, maní y queso, decorada con huevo duro y aceitunas.",
    imagen: "https://drive.google.com/file/d/1sWTPLIXvbCr9EGe18JkD19fZBBd-QVue/view?usp=drive_link",
    ingredientes: [
      "4 ajíes mirasol secos",
      "2 ajíes amarillos frescos sin venas ni semillas",
      "1 cebolla roja mediana",
      "2 dientes de ajo",
      "200 gramos de queso paria o queso fresco serrano",
      "1 cucharada colmada de maní tostado",
      "50 gramos de galletas de vainilla o galletas de soda",
      "½ taza de leche evaporada",
      "Aceite vegetal",
      "Sal al gusto",
      "Hojas de lechuga",
      "2 huevos duros",
      "Aceitunas negras para decorar",
    ],
    preparacion: [
      "Remojar los ajíes mirasol en agua caliente para suavizarlos y retirar las semillas y venas de los ajíes amarillos.",
      "En una sartén con aceite, dorar la cebolla picada, los ajos, los ajíes amarillos y mirasol, el maní, las galletas y el queso, moviendo constantemente durante 5 minutos. Añadir un chorrito de agua si es necesario.",
      "Retirar del fuego y dejar enfriar un poco.",
      "Licuar la mezcla con la leche evaporada poco a poco hasta obtener una salsa cremosa y homogénea. Sazonar con sal al gusto.",
      "Cocer las papas con cáscara, pelarlas y cortarlas en rodajas gruesas.",
      "Colocar hojas de lechuga en un plato, disponer las rodajas de papa encima y bañar con la salsa de ocopa.",
      "Decorar con rodajas de huevo duro y aceitunas negras.",
    ]
  },
  {
    id: 13,
    nombre: "Sopa Criolla",
    categoria: "caldo",
    descripcion: "Deliciosa sopa peruana con fideos, carne y un toque de leche.",
    imagen: "https://drive.google.com/file/d/1hYiGMGIovG2ADUHDknKnfRjU-IYQniId/view?usp=drive_link",
    ingredientes: [
      "250g de carne de res cortada en tiras finas",
      "200g de fideos cabello de ángel",
      "2 cebollas rojas picadas",
      "2 tomates pelados y picados",
      "2 ajíes amarillos picados",
      "3 dientes de ajo molidos",
      "1 cucharada de pasta de ají panca",
      "1/2 taza de leche evaporada",
      "4 huevos",
      "1 cucharada de orégano seco",
      "2 litros de caldo de carne",
      "Aceite vegetal",
      "Sal y pimienta al gusto",
      "Perejil picado para decorar",
    ],
    preparacion: [
      "En una olla grande, calentar aceite y sofreír la cebolla, ajo y ají amarillo hasta que estén transparentes.",
      "Añadir el tomate y la pasta de ají panca, cocinar por 3 minutos más.",
      "Agregar la carne y cocinar hasta que cambie de color.",
      "Incorporar el caldo de carne y llevar a ebullición.",
      "Añadir los fideos y cocinar según las instrucciones del paquete.",
      "Agregar la leche evaporada y el orégano.",
      "Romper los huevos directamente en la sopa, uno por uno, y dejar que se cocinen.",
      "Sazonar con sal y pimienta al gusto.",
      "Servir caliente, decorado con perejil picado.",
    ],
  },
  {
    id: 14,
    nombre: "Aguadito de Pollo",
    categoria: "caldo",
    descripcion: "Reconfortante sopa verde de pollo con arroz y verduras.",
    imagen: "https://drive.google.com/file/d/1MVYsH5asbW8etAzpji2-A0YF0EY_4Njg/view?usp=drive_link",
    ingredientes: [
      "1 pollo entero cortado en presas",
      "1 taza de arroz",
      "1 manojo grande de culantro (cilantro)",
      "1 cebolla roja picada",
      "3 dientes de ajo picados",
      "2 ajíes amarillos picados",
      "1 pimiento rojo picado",
      "1 zanahoria picada en cubos",
      "1 taza de arvejas frescas",
      "2 papas amarillas cortadas en cubos",
      "1 choclo cortado en rodajas",
      "2 litros de agua",
      "Aceite vegetal",
      "Sal y pimienta al gusto",
    ],
    preparacion: [
      "Licuar el culantro con un poco de agua para obtener un jugo verde intenso.",
      "En una olla grande, calentar aceite y sofreír la cebolla, ajo y ají amarillo.",
      "Añadir el pollo y dorar ligeramente por todos lados.",
      "Agregar el agua y llevar a ebullición. Cocinar el pollo por 20 minutos.",
      "Incorporar el arroz, la zanahoria, el pimiento y las papas.",
      "Cuando el arroz esté casi cocido, añadir las arvejas y el choclo.",
      "Agregar el jugo de culantro y cocinar por 5 minutos más.",
      "Sazonar con sal y pimienta al gusto.",
      "Servir caliente con una rodaja de choclo en cada plato.",
    ],
  },
  {
    id: 15,
    nombre: "Chicha Morada",
    categoria: "bebida",
    descripcion: "Refrescante bebida peruana hecha a base de maíz morado.",
    imagen: "https://drive.google.com/file/d/17CPGv618vt1l9RUxoPd7_xSyEvyIbooC/view?usp=drive_link",
    ingredientes: [
      "1kg de maíz morado",
      "2 manzanas cortadas en trozos",
      "1 piña cortada en trozos",
      "2 ramas de canela",
      "4 clavos de olor",
      "Cáscara de 1 limón",
      "3 litros de agua",
      "Jugo de 3 limones",
      "1 taza de azúcar",
      "Hielo al gusto",
    ],
    preparacion: [
      "Lavar bien el maíz morado y colocarlo en una olla grande con el agua.",
      "Añadir la canela, clavos de olor, cáscara de limón, manzanas y piña.",
      "Hervir por 45 minutos a fuego medio.",
      "Colar y dejar enfriar.",
      "Agregar el azúcar y el jugo de limón. Mezclar bien.",
      "Refrigerar por al menos 2 horas.",
      "Servir con hielo y trozos de fruta si se desea.",
    ],
  },
  {
    id: 16,
    nombre: "Pisco Sour",
    categoria: "bebida",
    descripcion: "Cóctel emblemático del Perú a base de pisco, limón y clara de huevo.",
    imagen: "https://drive.google.com/file/d/1vnHpGAbMVCvoAz17AIeo4rkaH762I62Q/view?usp=drive_link",
    ingredientes: [
      "3 onzas de pisco",
      "1 onza de jarabe de goma o almíbar",
      "1 onza de jugo de limón recién exprimido",
      "1 clara de huevo",
      "Hielo",
      "Amargo de Angostura",
      "Canela en polvo para decorar",
    ],
    preparacion: [
      "En una coctelera, añadir el pisco, jarabe de goma, jugo de limón y clara de huevo.",
      "Agitar vigorosamente sin hielo por 15 segundos (dry shake).",
      "Añadir hielo y agitar nuevamente por 15 segundos más.",
      "Colar en una copa fría.",
      "Añadir unas gotas de Amargo de Angostura sobre la espuma.",
      "Espolvorear canela en polvo y servir inmediatamente.",
    ],
  },
  {
    id: 17,
    nombre: "Chicha de Jora",
    categoria: "bebida",
    descripcion: "Bebida ancestral andina fermentada a base de maíz jora, tradicional en la sierra peruana.",
    imagen: "https://drive.google.com/file/d/1sxfX4KbOfn24zy1ccxI0JxKvi1FIPNVh/view?usp=drive_link",
    ingredientes: [
      "500 g de maíz jora",
      "3 litros de agua",
      "100 g de azúcar (opcional)",
      "Corteza de piña (opcional)",
      "Clavos de olor y canela (opcional)"
    ],
    preparacion: [
      "Lavar el maíz jora y hervirlo en una olla grande con el agua durante 2 a 3 horas.",
      "Agregar la corteza de piña, clavos de olor y canela si se desea aromatizar.",
      "Dejar enfriar y colar el líquido.",
      "Verter el líquido en un recipiente de barro o vidrio y dejar fermentar de 2 a 4 días.",
      "Agregar azúcar al gusto si se prefiere más dulce.",
      "Servir fría o a temperatura ambiente."
    ]
  },
  {
    id: 18,
    nombre: "Limonada",
    categoria: "bebida",
    descripcion: "Refrescante bebida a base de jugo de limón, agua y azúcar, ideal para combatir el calor.",
    imagen: "https://drive.google.com/file/d/1OK_QQ9pB0wynYeu4auXtTEgYMyYCh2C-/view?usp=drive_link",
    ingredientes: [
      "1 taza de jugo de limón fresco",
      "1 litro de agua fría",
      "1/2 taza de azúcar (ajustar al gusto)",
      "Cubos de hielo",
      "Rodajas de limón para decorar"
    ],
    preparacion: [
      "Exprimir los limones hasta obtener 1 taza de jugo.",
      "En una jarra grande, mezclar el jugo de limón con el azúcar hasta disolver.",
      "Agregar el agua fría y mezclar bien.",
      "Añadir cubos de hielo y decorar con rodajas de limón.",
      "Servir bien fría."
    ]
  },
  {
    id: 19,
    nombre: "Emoliente",
    categoria: "bebida",
    descripcion: "Bebida tradicional peruana a base de hierbas, cebada y linaza, consumida caliente y conocida por sus propiedades medicinales.",
    imagen: "https://drive.google.com/file/d/1Y2zIeYJijhYN_ZxHoQboDWHukmpaIVPO/view?usp=drive_link",
    ingredientes: [
      "2 litros de agua",
      "1/4 taza de cebada perlada",
      "2 cucharadas de linaza",
      "1 rama de cola de caballo",
      "1 rama de hierba luisa",
      "1 rama de boldo",
      "1 rama de alfalfa",
      "Jugo de limón al gusto",
      "Miel o azúcar al gusto"
    ],
    preparacion: [
      "En una olla grande, hervir el agua con la cebada y la linaza durante 30 minutos.",
      "Agregar las hierbas (cola de caballo, hierba luisa, boldo y alfalfa) y hervir por 10 minutos más.",
      "Colar la bebida y dejar entibiar.",
      "Endulzar con miel o azúcar y añadir jugo de limón al gusto.",
      "Servir caliente."
    ]
  },
  {
    id: 20,
    nombre: "Masato",
    categoria: "bebida",
    descripcion: "Bebida amazónica fermentada a base de yuca, tradicional en la selva peruana.",
    imagen: "https://drive.google.com/file/d/1YhxSIyvKNF2YuRlUm0AzI9H7kJRgbcEA/view?usp=drive_link",
    ingredientes: [
      "1 kg de yuca",
      "2 litros de agua",
      "Azúcar al gusto"
    ],
    preparacion: [
      "Pelar y cortar la yuca en trozos.",
      "Hervir la yuca en agua hasta que esté bien cocida y suave.",
      "Escurrir y triturar la yuca hasta obtener una masa homogénea.",
      "Agregar agua poco a poco hasta lograr una bebida espesa.",
      "Añadir azúcar al gusto y mezclar bien.",
      "Dejar fermentar la mezcla a temperatura ambiente durante 1 a 3 días según la intensidad deseada.",
      "Servir fría."
    ]
  },
  {
    id: 21,
    nombre: "Arroz Zambito",
    categoria: "postre",
    descripcion: "Postre peruano similar al arroz con leche, con chancaca, pasas, coco rallado y especias que le dan un color y sabor característico.",
    imagen: "https://drive.google.com/file/d/1yf_yPm9cRiTyeZB1SYQAJhz1F3dKDlBx/view?usp=drive_link",
    ingredientes: [
      "1 taza de arroz de grano largo",
      "4 tazas de agua",
      "1 bastón de canela",
      "2 clavos de olor",
      "1 taza de chancaca (panela) rallada",
      "200 ml de leche evaporada",
      "150 ml de leche condensada",
      "1/4 taza de pasas",
      "1/4 taza de coco rallado",
      "Canela en polvo para espolvorear"
    ],
    preparacion: [
      "En una olla, hervir el agua con la canela y los clavos de olor.",
      "Agregar el arroz y cocinar a fuego medio hasta que esté blando y el agua casi se evapore.",
      "En otra olla, disolver la chancaca en un poco de agua y cocinar hasta obtener una miel espesa.",
      "Incorporar la miel de chancaca al arroz cocido, mezclar suavemente para no romper los granos.",
      "Agregar la leche evaporada, leche condensada, pasas y coco rallado, mezclar y cocinar a fuego bajo por unos minutos.",
      "Servir en porciones y espolvorear canela en polvo al gusto."
    ]
  },
  {
    id: 22,
    nombre: "Arroz con Leche",
    categoria: "postre",
    descripcion: "Clásico postre cremoso hecho con arroz, leche, azúcar y canela, muy popular en Perú y Latinoamérica.",
    imagen: "https://drive.google.com/file/d/15sr9SYmRdzuWCxk90L8kNP_mwHfo1mvX/view?usp=drive_link",
    ingredientes: [
      "1 taza de arroz",
      "4 tazas de leche",
      "1 taza de azúcar",
      "1 bastón de canela",
      "Cáscara de limón",
      "Canela en polvo para decorar"
    ],
    preparacion: [
      "Lavar el arroz y cocinarlo en agua hasta que esté casi tierno.",
      "Agregar la leche, la canela y la cáscara de limón, cocinar a fuego bajo removiendo constantemente.",
      "Incorporar el azúcar y seguir cocinando hasta que la mezcla espese y el arroz esté completamente cocido.",
      "Retirar la canela y la cáscara de limón.",
      "Servir frío o tibio, espolvoreando canela en polvo."
    ]
  },
  {
    id: 23,
    nombre: "Crema Volteada",
    categoria: "postre",
    descripcion: "Versión peruana del flan, dulce y suave a base de huevos, leche y azúcar caramelizada.",
    imagen: "https://drive.google.com/file/d/1dyiKrpqPZeve-8mBOBAD1plBJ1z93bLR/view?usp=drive_link",
    ingredientes: [
      "6 huevos",
      "1 lata de leche evaporada",
      "1 lata de leche condensada",
      "1 taza de azúcar",
      "1 cucharadita de esencia de vainilla"
    ],
    preparacion: [
      "Preparar un caramelo con el azúcar en una olla hasta que tome color dorado y verterlo en un molde para flan.",
      "En un bol, batir los huevos con la leche evaporada, leche condensada y vainilla hasta integrar.",
      "Verter la mezcla en el molde con el caramelo.",
      "Cocinar a baño María en horno precalentado a 180°C por aproximadamente 50 minutos o hasta que cuaje.",
      "Dejar enfriar, desmoldar y servir."
    ]
  },
  {
    id: 24,
    nombre: "Queso Helado",
    categoria: "postre",
    descripcion: "Postre frío típico de la región norte del Perú, hecho con leche, canela, clavo y coco rallado, con textura cremosa y granulada.",
    imagen: "https://drive.google.com/file/d/1c5wX-o2dKxwmo-S4rIT8iN8dv-1NHXlo/view?usp=drive_link",
    ingredientes: [
      "1 litro de leche",
      "300 g de azúcar",
      "1 bastón de canela",
      "3 clavos de olor",
      "1 taza de coco rallado",
      "1 cucharadita de esencia de vainilla"
    ],
    preparacion: [
      "Hervir la leche con la canela y los clavos de olor para aromatizar.",
      "Agregar el azúcar y el coco rallado, cocinar a fuego bajo hasta que la mezcla espese ligeramente.",
      "Retirar las especias y añadir la vainilla.",
      "Dejar enfriar y llevar al congelador, removiendo cada cierto tiempo para evitar cristales de hielo y obtener textura cremosa.",
      "Servir frío."
    ]
  },
  {
    id: 25,
    nombre: "Flan",
    categoria: "postre",
    descripcion: "Postre clásico de huevo y leche con caramelo, suave y dulce, muy popular en la gastronomía peruana.",
    imagen: "https://drive.google.com/file/d/1ZIbdA7B7j4Zd2_ugTpBBe5S4vnD2nmq-/view?usp=drive_link",
    ingredientes: [
      "4 huevos",
      "1 taza de leche",
      "1 taza de azúcar",
      "1 cucharadita de esencia de vainilla"
    ],
    preparacion: [
      "Preparar un caramelo con el azúcar y verterlo en un molde para flan.",
      "Batir los huevos con la leche y la esencia de vainilla.",
      "Verter la mezcla en el molde con el caramelo.",
      "Cocinar a baño María en horno precalentado a 180°C durante 40-45 minutos o hasta que cuaje.",
      "Dejar enfriar, desmoldar y servir."
    ]
  },
  {
    id: 26,
    nombre: "Papa a la Huancaína",
    categoria: "entrada",
    descripcion: "Clásica entrada peruana de papas sancochadas cubiertas con una cremosa salsa a base de ají amarillo, queso fresco y galletas de soda.",
    imagen: "https://drive.google.com/file/d/1slKIiKgssJ48al8BZbR1VxhZ3srAhkIy/view?usp=drive_link",
    ingredientes: [
      "4 papas amarillas medianas",
      "3 ajíes amarillos sin venas ni pepas",
      "1/2 cebolla roja",
      "200 g de queso fresco",
      "6 galletas de soda",
      "3/4 taza de leche evaporada",
      "1/4 taza de aceite vegetal",
      "Sal y pimienta al gusto",
      "Hojas de lechuga",
      "Huevos duros para decorar",
      "Aceitunas negras para decorar"
    ],
    preparacion: [
      "Hervir las papas hasta que estén tiernas, pelar y cortar en rodajas.",
      "Saltear la cebolla, ají amarillo y ajo en un poco de aceite hasta dorar.",
      "Licuar la mezcla con el queso fresco, galletas de soda, leche evaporada y aceite hasta obtener una salsa cremosa.",
      "Sazonar con sal y pimienta.",
      "Servir las papas sobre hojas de lechuga, cubrir con la salsa y decorar con huevo duro y aceitunas."
    ]
  },
  {
    id: 27,
    nombre: "Tamales Peruanos",
    categoria: "entrada",
    descripcion: "Delicioso tamal peruano hecho con masa de maíz, relleno de carne, aceitunas y especias, envuelto en hojas de plátano y cocido al vapor.",
    imagen: "https://drive.google.com/file/d/14slGZd2PVU71JwrQSavW5jCfppiXxJyb/view?usp=drive_link",
    ingredientes: [
      "500 g de harina de maíz amarillo",
      "250 g de manteca de cerdo",
      "1 taza de caldo de pollo",
      "500 g de carne de cerdo o pollo cocida y deshilachada",
      "2 cebollas picadas",
      "2 dientes de ajo picados",
      "Aceitunas negras",
      "Huevos cocidos",
      "Ají amarillo molido",
      "Sal y pimienta al gusto",
      "Hojas de plátano para envolver"
    ],
    preparacion: [
      "Preparar la masa mezclando la harina de maíz con la manteca y el caldo hasta obtener una masa suave.",
      "Sofreír la cebolla, ajo y ají amarillo, agregar la carne deshilachada, salpimentar y cocinar unos minutos.",
      "En las hojas de plátano, colocar una porción de masa, agregar el relleno, aceitunas y huevo cocido.",
      "Cerrar y amarrar los tamales con tiras de hoja de plátano.",
      "Cocinar al vapor por aproximadamente 1 hora.",
      "Dejar enfriar un poco antes de servir."
    ]
  },
  {
    id: 28,
    nombre: "Choclo con Queso",
    categoria: "entrada",
    descripcion: "Sencilla y tradicional entrada peruana que combina choclo cocido con queso fresco, ideal para acompañar cualquier comida.",
    imagen: "https://drive.google.com/file/d/1qAD6MQgzdV4xFknetAYea8QOdYdsfhrA/view?usp=drive_link",
    ingredientes: [
      "2 choclos grandes",
      "200 g de queso fresco",
      "Sal al gusto"
    ],
    preparacion: [
      "Cocer los choclos enteros en agua con sal hasta que estén tiernos.",
      "Pelarlos y cortar en trozos o servir enteros.",
      "Acompañar con trozos de queso fresco.",
      "Servir frío o a temperatura ambiente."
    ]
  },
  {
    id: 29,
    nombre: "Wantanes Fritos",
    categoria: "entrada",
    descripcion: "Crujientes bocados fritos rellenos de carne, pollo o verduras, muy populares como entrada o aperitivo en la gastronomía peruana.",
    imagen: "https://drive.google.com/file/d/1jVUluFFqMcCL1gjlrjnT1jo6h62eYa6q/view?usp=drive_link",
    ingredientes: [
      "20 hojas de wantán",
      "200 g de carne molida o pollo deshilachado",
      "1 cebolla pequeña picada",
      "2 dientes de ajo picados",
      "1 cucharada de salsa de soja",
      "Sal y pimienta al gusto",
      "Aceite para freír"
    ],
    preparacion: [
      "Saltear la carne con cebolla, ajo, salsa de soja, sal y pimienta hasta cocinar completamente.",
      "Dejar enfriar el relleno.",
      "Colocar una cucharadita de relleno en cada hoja de wantán y doblar formando triángulos o paquetitos.",
      "Freír en abundante aceite caliente hasta que estén dorados y crujientes.",
      "Escurrir sobre papel absorbente y servir con salsa de ají o salsa tártara."
    ]
  },
  {
    id: 30,
    nombre: "Chilcano de Pescado",
    categoria: "entrada",
    descripcion: "Caldo ligero y sabroso hecho con pescado fresco, aromatizado con hierbas y especias, ideal como entrada en la costa peruana.",
    imagen: "https://drive.google.com/file/d/1CIzKorZIBrvMpeIDfORc6hDEYz9WcYbu/view?usp=drive_link",
    ingredientes: [
      "500 g de pescado fresco (merluza, corvina o similar)",
      "1 cebolla picada",
      "2 dientes de ajo picados",
      "1 tomate picado",
      "1 ají amarillo sin venas ni pepas",
      "1 rama de perejil",
      "1 rama de cilantro",
      "Sal y pimienta al gusto",
      "1 litro de agua",
      "Jugo de limón al gusto"
    ],
    preparacion: [
      "En una olla, sofreír la cebolla, ajo, tomate y ají amarillo hasta que estén tiernos.",
      "Agregar el agua y llevar a ebullición.",
      "Incorporar el pescado cortado en trozos y cocinar a fuego medio hasta que esté cocido.",
      "Añadir perejil, cilantro, sal y pimienta.",
      "Retirar del fuego y agregar jugo de limón al gusto.",
      "Servir caliente."
    ]
  },
  {
    id: 31,
    nombre: "Caldo de Gallina",
    categoria: "caldo",
    descripcion: "Sopa tradicional peruana hecha con gallina criolla, verduras y fideos, muy reconfortante y nutritiva.",
    imagen: "https://drive.google.com/file/d/1zTvQaFvbMxukX2_3m_IL4H2ITlg7Icr_/view?usp=drive_link",
    ingredientes: [
      "1 gallina criolla cortada en presas",
      "2 litros de agua",
      "1 taza de fideos cabello de ángel",
      "2 papas amarillas peladas y cortadas en trozos",
      "1 cebolla picada",
      "3 dientes de ajo picados",
      "1 zanahoria picada",
      "1 rama de apio",
      "1 manojo de perejil",
      "Sal y pimienta al gusto",
      "1 huevo duro para decorar",
      "Culantro para decorar"
    ],
    preparacion: [
      "En una olla grande, colocar la gallina con el agua y llevar a ebullición.",
      "Agregar la cebolla, ajo, zanahoria, apio, sal y pimienta.",
      "Cocinar a fuego medio hasta que la gallina esté tierna.",
      "Añadir las papas y los fideos, cocinar hasta que estén suaves.",
      "Rectificar la sazón y retirar el apio.",
      "Servir caliente, decorando con huevo duro picado y culantro."
    ]
  },
  {
    id: 32,
    nombre: "Menestrón",
    categoria: "caldo",
    descripcion: "Sopa de origen italiano muy popular en Perú, con verduras, legumbres, fideos y carne, nutritiva y reconfortante.",
    imagen: "https://drive.google.com/file/d/18SIQoNx5XXRATzx4z7Rc_cDm5WYf7bjO/view?usp=drive_link",
    ingredientes: [
      "200 g de carne de res en trozos",
      "1 cebolla picada",
      "2 dientes de ajo picados",
      "2 papas cortadas en cubos",
      "1 zanahoria picada",
      "1 taza de frejoles cocidos",
      "1 taza de garbanzos cocidos",
      "1 taza de arvejas",
      "1 taza de fideos",
      "1 rama de apio",
      "1 tomate picado",
      "1 litro de caldo de carne",
      "Sal, pimienta y orégano al gusto",
      "Queso parmesano rallado para servir"
    ],
    preparacion: [
      "En una olla, sofreír la cebolla y ajo hasta dorar.",
      "Agregar la carne y sellar por todos lados.",
      "Añadir el tomate, apio, papas, zanahoria y caldo de carne.",
      "Cocinar hasta que la carne y verduras estén tiernas.",
      "Incorporar los frejoles, garbanzos, arvejas y fideos.",
      "Cocinar hasta que los fideos estén al dente.",
      "Sazonar con sal, pimienta y orégano.",
      "Servir caliente con queso parmesano rallado."
    ]
  },
  {
    id: 33,
    nombre: "Parihuela",
    categoria: "caldo",
    descripcion: "Caldo concentrado de mariscos variados, típico de la costa peruana, muy sabroso y picante.",
    imagen: "https://drive.google.com/file/d/1AM0y7WrF6TzUti9HD7vrbAx2YUaCtRjH/view?usp=drive_link",
    ingredientes: [
      "300 g de pescado fresco",
      "200 g de camarones",
      "150 g de calamares",
      "150 g de mejillones",
      "1 cebolla picada",
      "2 dientes de ajo picados",
      "1 tomate picado",
      "1 ají amarillo picado",
      "1 litro de caldo de pescado",
      "1 rama de perejil",
      "Sal, pimienta y comino al gusto",
      "Jugo de limón al gusto"
    ],
    preparacion: [
      "En una olla, sofreír la cebolla, ajo, ají amarillo y tomate.",
      "Agregar el caldo de pescado y llevar a ebullición.",
      "Incorporar los mariscos y cocinar hasta que estén tiernos.",
      "Sazonar con sal, pimienta, comino y jugo de limón.",
      "Añadir perejil picado antes de servir.",
      "Servir caliente."
    ]
  },
  {
    id: 34,
    nombre: "Patasca",
    categoria: "caldo",
    descripcion: "Sopa andina tradicional hecha con maíz mote, carne de res y mondongo, ideal para el frío de la sierra.",
    imagen: "https://drive.google.com/file/d/112N0QjQWw-c1RyDgX6bWU-__fSvqReKq/view?usp=drive_link",
    ingredientes: [
      "500 g de carne de res (falda o costilla)",
      "300 g de mondongo limpio y cortado",
      "2 tazas de maíz mote cocido",
      "1 cebolla picada",
      "2 dientes de ajo picados",
      "1 ají amarillo picado",
      "1 rama de hierba buena o hierba luisa",
      "Sal y pimienta al gusto",
      "1 litro de agua"
    ],
    preparacion: [
      "En una olla grande, cocinar la carne y el mondongo en agua hasta que estén tiernos.",
      "Agregar la cebolla, ajo y ají amarillo, cocinar unos minutos más.",
      "Incorporar el maíz mote y la hierba buena.",
      "Sazonar con sal y pimienta.",
      "Cocinar a fuego lento hasta que la sopa espese ligeramente.",
      "Servir caliente."
    ]
  },
  {
    id: 35,
    nombre: "Sancochado",
    categoria: "caldo",
    descripcion: "Plato contundente y nutritivo de la costa peruana, con caldo de res y variedad de verduras cocidas.",
    imagen: "https://drive.google.com/file/d/1m84e9U7J8lK7Vop-jdBlp6cRHs08wXD4/view?usp=drive_link",
    ingredientes: [
      "500 g de carne de res con hueso",
      "2 litros de agua",
      "2 papas grandes",
      "1 camote grande",
      "1 choclo cortado en rodajas",
      "1 zanahoria grande",
      "1 rama de repollo",
      "1 plátano verde",
      "Sal y pimienta al gusto",
      "Culantro para decorar"
    ],
    preparacion: [
      "En una olla grande, colocar la carne con el agua y llevar a ebullición.",
      "Cocinar a fuego medio hasta que la carne esté tierna.",
      "Agregar las papas, camote, choclo, zanahoria, repollo y plátano cortados.",
      "Cocinar hasta que las verduras estén suaves.",
      "Sazonar con sal y pimienta.",
      "Servir caliente decorado con culantro."
    ]
  },
  {
    id: 36,
    nombre: "Arroz con Pollo",
    categoria: "principal",
    descripcion: "Clásico plato peruano de arroz verde al cilantro cocinado con presas de pollo y verduras, acompañado de salsa criolla.",
    imagen: "https://drive.google.com/file/d/1wOHHy9JcrsuoNYe1CZhZJaltDtWGY2i8/view?usp=drive_link",
    ingredientes: [
      "5 presas de pollo",
      "3 tazas de arroz lavado",
      "1 cebolla picada en cuadritos",
      "1/2 pimiento picado en cuadritos o tiras",
      "1 zanahoria picada en cuadritos",
      "1 taza de arvejas",
      "1 taza de choclo desgranado",
      "1 manojo de cilantro",
      "2 dientes de ajo",
      "1/4 taza de aceite vegetal",
      "Sal y pimienta al gusto",
      "Salsa criolla para acompañar"
    ],
    preparacion: [
      "Licuar el cilantro con los dientes de ajo y un poco de agua para obtener una pasta verde.",
      "Sazonar el pollo con sal y pimienta y dorar en aceite caliente.",
      "Sofreír la cebolla, pimiento y zanahoria en la misma olla.",
      "Agregar la pasta de cilantro y cocinar hasta que el aceite se separe.",
      "Incorporar el arroz, arvejas y choclo, mezclar bien.",
      "Agregar el pollo y suficiente agua para cocinar el arroz.",
      "Cocinar a fuego medio-bajo hasta que el arroz esté tierno y el líquido se absorba.",
      "Servir acompañado de salsa criolla."
    ]
  },
  {
    id: 37,
    nombre: "Carapulcra Limeña",
    categoria: "principal",
    descripcion: "Guiso tradicional peruano hecho con papa seca, carne de cerdo, ajíes y especias, típico de Lima.",
    imagen: "https://drive.google.com/file/d/1gxag_MlYAzc3jZPEnpUKR0lKiShfvHlj/view?usp=drive_link",
    ingredientes: [
      "300 g de papa seca remojada",
      "500 g de carne de cerdo cortada en trozos",
      "1 cebolla picada",
      "2 dientes de ajo picados",
      "2 cucharadas de ají panca molido",
      "1 cucharada de ají amarillo molido",
      "1/4 taza de aceite vegetal",
      "1 taza de caldo de carne",
      "Sal, pimienta y comino al gusto",
      "Maní tostado molido (opcional)"
    ],
    preparacion: [
      "Remojar la papa seca en agua hasta que se ablande y escurrir.",
      "En una olla, sofreír la cebolla y ajo en aceite hasta dorar.",
      "Agregar los ajíes molidos y cocinar unos minutos.",
      "Incorporar la carne de cerdo y sellar.",
      "Añadir la papa seca y el caldo, sazonar con sal, pimienta y comino.",
      "Cocinar a fuego lento hasta que la papa esté tierna y la salsa espese.",
      "Agregar maní molido si se desea y mezclar bien.",
      "Servir caliente acompañado con arroz blanco."
    ]
  },
  {
    id: 38,
    nombre: "Cuy Chactado",
    categoria: "principal",
    descripcion: "Plato tradicional andino que consiste en cuy frito crocante, sazonado con especias y servido con papas y salsa.",
    imagen: "https://drive.google.com/file/d/1xlJgwNW4I1bFVGOqMb0xxCmysw322XJU/view?usp=drive_link",
    ingredientes: [
      "1 cuy limpio y abierto",
      "Sal y pimienta al gusto",
      "Ajo molido",
      "Comino",
      "Aceite para freír",
      "Papas sancochadas para acompañar",
      "Salsa de ají para acompañar"
    ],
    preparacion: [
      "Sazonar el cuy con sal, pimienta, ajo y comino.",
      "Calentar abundante aceite en una sartén profunda.",
      "Freír el cuy hasta que esté dorado y crocante por ambos lados.",
      "Escurrir sobre papel absorbente.",
      "Servir acompañado de papas sancochadas y salsa de ají."
    ]
  },
  {
    id: 39,
    nombre: "Adobo Arequipeño",
    categoria: "principal",
    descripcion: "Guiso tradicional de cerdo marinado en chicha de jora y especias, típico de la región de Arequipa.",
    imagen: "https://drive.google.com/file/d/1TVLJ0N-tXVUgcA6sGvrs3MJhEjPkMfVr/view?usp=drive_link",
    ingredientes: [
      "1 kg de carne de cerdo en trozos",
      "1 taza de chicha de jora",
      "4 dientes de ajo molidos",
      "1 cebolla picada",
      "2 cucharadas de ají panca molido",
      "1 cucharadita de comino",
      "1 cucharadita de orégano",
      "Sal y pimienta al gusto",
      "Aceite vegetal"
    ],
    preparacion: [
      "Marinar la carne con ajo, ají panca, comino, orégano, sal, pimienta y chicha de jora por al menos 4 horas.",
      "En una olla, sofreír la cebolla en aceite hasta dorar.",
      "Agregar la carne con la marinada y cocinar a fuego medio hasta que esté tierna y la salsa espese.",
      "Servir caliente acompañado de arroz o pan."
    ]
  },
  {
    id: 40,
    nombre: "Olluquito con Carne",
    categoria: "principal",
    descripcion: "Guiso tradicional andino hecho con olluco, carne de res y especias, acompañado con arroz o papas.",
    imagen: "https://drive.google.com/file/d/195G0L6Kpq5fqLtNDcLJ8MhszC6zaHTa4/view?usp=drive_link",
    ingredientes: [
      "500 g de olluco pelado y cortado en tiras",
      "300 g de carne de res cortada en trozos",
      "1 cebolla picada",
      "2 dientes de ajo picados",
      "1 ají amarillo molido",
      "1/4 taza de aceite vegetal",
      "1 taza de caldo de carne",
      "Sal y pimienta al gusto",
      "Perejil picado para decorar"
    ],
    preparacion: [
      "Sofreír la cebolla y ajo en aceite hasta dorar.",
      "Agregar la carne y sellar por todos lados.",
      "Incorporar el ají amarillo y cocinar unos minutos.",
      "Añadir el olluco y el caldo, sazonar con sal y pimienta.",
      "Cocinar a fuego lento hasta que la carne y el olluco estén tiernos.",
      "Decorar con perejil picado y servir."
    ]
  },
  {
    id: 41,
    nombre: "Arroz Chaufa",
    categoria: "principal",
    descripcion: "Plato fusión chino-peruana hecho con arroz salteado, verduras, huevo y carne o pollo.",
    imagen: "https://drive.google.com/file/d/1KG5uHF1ELzIWv2NZZsC-ePq3QOJ6Pv-M/view?usp=drive_link",
    ingredientes: [
      "3 tazas de arroz cocido",
      "2 huevos batidos",
      "1 taza de pollo o carne picada",
      "1/2 taza de cebolla china picada",
      "1/2 taza de pimiento rojo picado",
      "2 dientes de ajo picados",
      "2 cucharadas de salsa de soja",
      "Aceite vegetal",
      "Sal y pimienta al gusto"
    ],
    preparacion: [
      "En una sartén grande, calentar aceite y hacer un omelette con los huevos batidos, reservar.",
      "Saltear el ajo, cebolla china y pimiento hasta que estén tiernos.",
      "Agregar la carne o pollo y cocinar hasta que esté listo.",
      "Incorporar el arroz cocido y mezclar bien.",
      "Agregar la salsa de soja, sal y pimienta.",
      "Agregar el omelette cortado en tiras y mezclar.",
      "Cocinar unos minutos más y servir caliente."
    ]
  },
  {
    id: 42,
    nombre: "Tacacho con Cecina",
    categoria: "principal",
    descripcion: "Plato típico de la selva peruana que combina puré de plátano verde con cecina ahumada y frita.",
    imagen: "https://drive.google.com/file/d/1AlBxNi8WJcOqDKAJdKp6pODeb3pT9DWh/view?usp=drive_link",
    ingredientes: [
      "4 plátanos verdes",
      "200 g de cecina ahumada",
      "Aceite para freír",
      "Sal al gusto"
    ],
    preparacion: [
      "Hervir los plátanos verdes hasta que estén blandos.",
      "Pelar y machacar los plátanos hasta formar un puré.",
      "Formar bolas con el puré y reservar.",
      "Freír la cecina en aceite hasta que esté crujiente.",
      "Freír las bolas de tacacho en aceite hasta dorar.",
      "Servir el tacacho acompañado de la cecina."
    ]
  },
];

// Si no hay datos en localStorage, guardar los datos iniciales
if (!localStorage.getItem("platosPeruanos")) {
  localStorage.setItem("platosPeruanos", JSON.stringify(platosPeruanos));
}